# Pour la création du .jar

FROM maven:3-eclipse-temurin-21-alpine as maven

WORKDIR /app

COPY . .

RUN mvn clean package

######

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from-maven target/backend-*.jar backend.jar

EXPOSE 8080

CMD ["java", "-jar", "backend.jar"]